### ISSUE TITLE
Could you please give an example of dump file?

### ISSUE THREAD

**Issue by yfgu** [level077/lua-resty-upstream-etcd#1]
Could you please give an example of dump file?
When I merge your module into my Nginx_Lua peoject and start the nginx, there is always an error in log file. At the first time, it creates one dump file /tmp/nginx_upstream. As what I understand, then it will read the dump file.  Because there is no data in the dump file,  an error will be thrown out.

**Comment by level077** [comment]
what's the error message?

**Comment by yfgu** [comment]
I've got the dump file.
But I have another issue. When I read the value by key-ip:port, there is no nodes under node. So I delete one for loop in watch function.

**Comment by yfgu** [comment]
I got it. I set the wrong dataset in etcd.
The directory should like this /upstream/{upstream name1}/server1(ip:port);/upstream/{upstream name1}/server2(ip:port)
