### ISSUE TITLE
b.set_current_peer(server) in balancer.lua

### ISSUE THREAD

**Issue by yfgu** [level077/lua-resty-upstream-etcd#2]
What's the module which contains the set_current_peer function?
I use openresty's lua-resty-core module. The function set_current_peer(addr, port) in balancer.lua has two parameters. But the balancer.lua of lua-resty-upstream-etcd calls the function which has only one parameter.

**Comment by level077** [comment]
https://github.com/agentzh/lua-resty-balancer

**Comment by yfgu** [comment]
I use openresty-1.9.15.1. 
The balancer.lua is under bundle/lua-resty-core-0.1.6/lib/ngx/.
Which balancer does your project use?

**Comment by level077** [comment]
i use openresty-1.11.2.1 and the lua-resty-core version is 0.1.8

**Comment by yfgu** [comment]
In the watch function of lua-resty-upstream-etcd/balancer.lua, the hash_server(name) is called. But the name use the key like 10.20.22.86:8010 instead of upstream name. When the the request comes, dyups.find(ngx.var.backend,ngx.var.remote_addr,ngx.var.hash_method) will be called in balancer.lua. I think that the first parameter is the upstream name. So there is no data will be read by the _M[name].

**Comment by yfgu** [comment]
I got it. I set the wrong dataset in etcd. It should be /upstream/{upstream name}/ip:port. I will try the multiple upstreams later.
