### ISSUE TITLE
pass ip:port as the addr and pass 0 as port to lua-resty-core/lib/ngx/balancer.lua

### ISSUE THREAD

**Issue by yfgu** [level077/lua-resty-upstream-etcd#4]
The b.set_current_peer(server) in the lua-resty-upstream-etcd/balancer.lua pass the 10.20.22.85:8010 to the _M.set_current_peer(addr, port) in lua-resty-core/lib/ngx/balancer.lua. So the port is 0 in lua-resty-core/lib/ngx/balancer.lua. But I get the correct forwarding. Is that correct? Does the C.ngx_http_lua_ffi_balancer_set_current_peer deal with the addr as ip:port and port as 0 correctly?

**Comment by level077** [comment]
the forwarding is correct,but i don't kown why.you can ask this question in https://groups.google.com/forum/#!forum/openresty

**Comment by yfgu** [comment]
Thanks.
I asked this question in https://github.com/agentzh/lua-resty-balancer/issues.
I will ask it in https://groups.google.com/forum/#!forum/openresty later if I still get no answer.
