### ISSUE TITLE
redis 报错 connect() failed (110: Connection timed out)

### ISSUE THREAD

**Issue by yfgu** [level077/lua-resty-upstream-etcd#5]
使用resty.redis模块，时不时会出现如下错误：
         connect() failed (110: Connection timed out)
如果重试用原先的sock实例再次connect一次，会不会还是连接不上。这个底层是用连接池的还是每次都是短连接？

**Comment by level077** [comment]
这里没用到redis啊，你是自己用redis写了一个？

**Comment by yfgu** [comment]
是用的https://github.com/CNSRE/ABTestingGateway的那块代码connectdb function在ABTestingGateway/lib/abtesting/utils/redis.lua里面

**Comment by level077** [comment]
这个就不清楚了，没用过。你得去问他们

**Comment by yfgu** [comment]
找到原因了，使我们配置的redis错了。我们把配置和代码标准化后分离了，测试环境的配置不知道什么时候被修改了。
奇怪的是，两台服务器代码配置一样，都配置了错误的redis,但是有1台不管怎么重启，都是转发数据到了正确的redis上。后来把配置改正确以后重启，2台都转发到了正确的redis。
