### ISSUE TITLE
nginx启动的时候报错

### ISSUE THREAD

**Issue by yfgu** [level077/lua-resty-upstream-etcd#6]
nginx多启动几次后，有时候会报以下错误，然后线程不工作了。
Error start watch: too many pending timers, context: ngx.timer

查看etcd链接（netstat|grep 2379|wc -l）,一直是24

**Comment by yfgu** [comment]
我把watch的中代码提取成单独的function了。
这个和nginx的启动没有关系，打印了下，看到watch执行了512次，然后就报错了。lua_max_pending_timers不是说默认1024个么？ 不知道代码提取哪里有问题，居然pending了。

**Comment by yfgu** [comment]
已经解决

**Comment by level077** [comment]
什么原因？

**Comment by yfgu** [comment]
增加watch时间就可以了,启动太多的进程了
